export const DataObj = {
    title: {
      arrOfTitle: [
        ["student_name", "მოსწავლის სახელი",],
        ["student_age", "მოსწავლის ასაკი",],
        ["student_group", "მოსწავლის ჯგუფი",],
        ["student_speed", "სიჩქარე"],
        ["student_github", "გიტი / github"],
        ["student_facebook", "Facebook"],
        ["parent_name", "მშობლის სახელი"],
        ["parent_facebook", "მშობლის Facebook"],
        ["student_level", "დონე"],
        ["student_role", "როლი"],
        ["leader_of_student", "მოსწავლის ლიდერი"],
        ["Score_from_leader", "ქულა ლიდერისგან"],
        ["score_from_quiz", "ქულა გამოცდიდან"],
        ["score_from_github", "ქულა GitHub-ზე"]
      ],
      studentsData: [
        {
          student_name: "დავით გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },
        {
          student_name: "დავით გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },
        {
          student_name: "დავით გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },



        {
          student_name: "დავით გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },
        {
          student_name: "დავით გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },
         {
          student_name: "დავით გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },
        {
          student_name: "ვაჯა გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },
        {
          student_name: "გიორგი გრძელშივლიდასდა",
          student_age: 19,
          student_group: 33,
          student_speed: 4,
          student_github: "https://github.com",
          student_facebook: "https://www.facebook.com/daviti",
          parent_name: "გიორგი სმითი",
          parent_facebook: "https://www.facebook.com/giorgis",
          student_level: 1,
          student_role: "მოსწავლე",
          leader_of_student: "მარიამი",
          Score_from_leader: 85,
          score_from_quiz: 92,
          score_from_github: 78,
        },
      ]
    }
  
  }
  